name: progress_soft_app
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  http: ^1.2.2
  dio: ^5.5.0+1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  intl: ^0.18.0
  lottie: ^3.1.2
  flutter_libphonenumber: ^2.2.3
  phone_number: ^2.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter_launcher_icons:
 android: "launcher_icon"
 ios: true
 min_sdk_android: 21
 image_path: "assets/images/ic_launcher_monochrome.png"
 image_path_ios: "assets/images/ic_launcher_monochrome.png"
 image_path_android: "assets/images/ic_launcher_monochrome.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/animations/
    - assets/images/


  fonts:
    - family: SFArabic
      fonts:
        - asset: assets/fonts/SFArabic-Regular.ttf
